# Generated by Django 4.0.4 on 2022-11-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, null=True)),
                ('nivel', models.CharField(choices=[('Preescolar', 'Preescolar'), ('Básica Primaria', 'Básica Primaria'), ('Básica Secundaria', 'Básica Secundaria'), ('Media', 'Media'), ('Técnica', 'Técnica'), ('Tecnológica', 'Tecnológica'), ('Profesional', 'Profesional')], max_length=255, null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
