# Generated by Django 4.0.4 on 2022-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_educationlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(choices=[('Barranquilla', 'Barranquilla'), ('Bógota', 'Bógota'), ('Medellín', 'Medellín'), ('Cali', 'Cali'), ('Santa Marta', 'Santa Marta'), ('Amazonas', 'Amazonas'), ('Otros', 'Otros'), ('Internacional', 'Internacional')], max_length=255, null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
